### ISSUE TITLE
我一下载，然后去登录就报错（登录失败：Cannot read property 'status' of undefined）

### ISSUE THREAD

**Issue by FZS999** [imlinhanchao/vsc-pwl-chat#2]
![image](https://user-images.githubusercontent.com/57242117/153527473-2a30352c-cd92-4881-b998-a8d280964fc8.png)

**Comment by FZS999** [comment]
我不知道是我电脑配置问题，还是啥问题，反正就是登录不进去，账号密码肯定是没问题的

**Comment by imlinhanchao** [comment]
確認一下是否有開代理，把 fishpi.cn 加入白名單。

**Comment by FZS999** [comment]
嗯嗯嗯。。。身为小白的我，完全没明白该怎么弄，是要打开代理还是关闭，把fishpi.cn加入白目录，这个的话怎么加

**Comment by FZS999** [comment]
![image](https://user-images.githubusercontent.com/57242117/153544028-af50b99d-c3c4-4fc0-8729-0203e6bd4431.png)
是要在这个里面配置吗，我这里面好像是没有配置什么代理的

**Comment by imlinhanchao** [comment]
代理開啓繞過大陸網站，代理軟件找一下設置直連域名的地方。

**Comment by imlinhanchao** [comment]
你有開翻墻軟件嗎？

**Comment by FZS999** [comment]
需要开吗

**Comment by imlinhanchao** [comment]
不需要，你使用客戶端可以登錄嗎？

**Comment by FZS999** [comment]
可以的，谷歌登录没问题

**Comment by imlinhanchao** [comment]
我是指桌面客戶端：https://github.com/imlinhanchao/pwl-chat/

**Comment by FZS999** [comment]
不行
![image](https://user-images.githubusercontent.com/57242117/153544859-7a8effa1-ae19-44a3-bba5-fb3d26b37206.png)

**Comment by imlinhanchao** [comment]
release有打包好的，可以直接下載運行

**Comment by imlinhanchao** [comment]
https://github.com/imlinhanchao/pwl-chat/releases

**Comment by FZS999** [comment]
![image](https://user-images.githubusercontent.com/57242117/153546715-c84ce8b0-c82e-4075-8d3b-a0b2d6f2dbf9.png)
可以登录

**Comment by imlinhanchao** [comment]
這就很奇怪了，你確定你的版本是最新的0.0.12嗎？
